#!/usr/bin/env python3
"""
Regenerate tools/companion/vectors/frames.json.

The vector file is the cross-language contract: the Python, TypeScript, and
Swift codecs each run it in their own test suite, and the Kotlin and firmware
codecs are written against it. Regenerate only when the protocol itself
changes, and expect every implementation's tests to move with it.

Deterministic by construction — no clock, no randomness — so an unchanged
protocol regenerates a byte-identical file.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import medusa_companion as mc

OUT = Path(__file__).resolve().parents[1] / "vectors" / "frames.json"


def encode_case(name, payload, msg_id, max_frame_len, why):
    return {
        "name": name,
        "why": why,
        "payload_hex": payload.hex(),
        "msg_id": msg_id,
        "max_frame_len": max_frame_len,
        "frames_hex": [f.hex() for f in mc.encode_frames(payload, msg_id, max_frame_len)],
    }


def build():
    envelope = mc.encode_envelope("cmd", "scan.wifi.start", "c0ffee", {"channels": [1, 6, 11]})

    encode = [
        encode_case(
            "empty-payload", b"", 0, 32,
            "An empty payload is still one frame; 'no data' and silence must differ on the wire.",
        ),
        encode_case(
            "two-bytes", b"hi", 1, 64,
            "Smallest non-trivial frame; pins the exact header byte order.",
        ),
        encode_case(
            "envelope-single-frame", envelope, 2, 244,
            "A real command envelope that fits one negotiated-MTU BLE notification.",
        ),
        encode_case(
            "envelope-default-mtu", envelope, 3, 20,
            "The same envelope before MTU negotiation: 20 usable bytes, 8 of payload each.",
        ),
        encode_case(
            "exact-boundary", b"x" * (244 - mc.HEADER_LEN), 4, 244,
            "Payload exactly fills one frame; must not emit a spurious empty second fragment.",
        ),
        encode_case(
            "one-over-boundary", b"x" * (244 - mc.HEADER_LEN + 1), 5, 244,
            "One byte past the boundary; the tail fragment carries a single byte.",
        ),
        encode_case(
            "multi-fragment-1024", bytes(range(256)) * 4, 42, 244,
            "Full byte range, five fragments; catches sign-extension and endianness bugs.",
        ),
    ]

    # Failure vectors. Each is a case where accepting the data is worse than
    # rejecting it, so every implementation must reject it with the same code.
    long_frames = mc.encode_frames(b"a" * 600, msg_id=9, max_frame_len=244)

    def tamper(frame, offset, mask=0xFF):
        raw = bytearray(frame)
        raw[offset] ^= mask
        return bytes(raw)

    decode_errors = [
        {
            "name": "truncated-header",
            "why": "A frame shorter than the 12-byte header has no trustworthy fields at all.",
            "frames_hex": [long_frames[0][:8].hex()],
            "code": "proto.short",
        },
        {
            "name": "unknown-version",
            "why": "A future version must be refused, never guessed at.",
            "frames_hex": [tamper(long_frames[0], 0, 0x03).hex()],
            "code": "proto.version",
        },
        {
            "name": "orphan-fragment",
            "why": "A mid-message fragment whose start was never seen cannot be reassembled.",
            "frames_hex": [long_frames[1].hex()],
            "code": "proto.orphan",
        },
        {
            "name": "out-of-order",
            "why": "Both transports are ordered; a gap means loss, not reordering.",
            "frames_hex": [long_frames[0].hex(), long_frames[2].hex()],
            "code": "proto.order",
        },
        {
            "name": "spliced-checksum",
            "why": "A fragment disagreeing about the message's crc is splicing two messages.",
            "frames_hex": [long_frames[0].hex(), tamper(long_frames[1], 8).hex()],
            "code": "proto.mismatch",
        },
        {
            "name": "corrupt-payload",
            "why": "Bit-flipped payload must fail the whole-message checksum, not pass silently.",
            "frames_hex": [
                long_frames[0].hex(),
                tamper(long_frames[1], mc.HEADER_LEN).hex(),
                *[f.hex() for f in long_frames[2:]],
            ],
            "code": "proto.crc",
        },
    ]

    return {
        "protocol": "medusa-companion",
        "version": mc.VERSION,
        "header_len": mc.HEADER_LEN,
        "note": (
            "Generated by tools/companion/python/generate_vectors.py. "
            "The contract every codec must satisfy; see wiki/design/companion-protocol.md."
        ),
        "encode": encode,
        "decode_errors": decode_errors,
    }


def build_tsv(data):
    """A flat, dependency-free view of the same encode vectors.

    Parsing JSON without a library is miserable in C and merely annoying in
    Java, and neither the firmware conformance check nor the JVM semantics
    probe should need a JSON dependency just to read test data. One case per
    line, tab separated:

        name <TAB> msg_id <TAB> max_frame_len <TAB> payload_hex <TAB> frame_hex,frame_hex,...

    An empty payload is the empty string in field 4, which is why the format is
    tab separated rather than whitespace separated.
    """
    lines = ["# name\tmsg_id\tmax_frame_len\tpayload_hex\tframes_hex(comma separated)"]
    for case in data["encode"]:
        lines.append("\t".join([
            case["name"],
            str(case["msg_id"]),
            str(case["max_frame_len"]),
            case["payload_hex"],
            ",".join(case["frames_hex"]),
        ]))
    return "\n".join(lines) + "\n"


def build_errors_tsv(data):
    """The decode-error cases, in the same dependency-free form.

    These matter more to a new codec than the encode cases do. Getting bytes
    out is the easy half; refusing the right bytes is where implementations
    quietly diverge, and a codec that accepts a truncated header or a bad CRC
    will look perfectly healthy against the encode vectors alone.

        name <TAB> expected_code <TAB> frame_hex,frame_hex,...

    Frames are fed in order and the expected code must be raised by one of
    them — not necessarily the first, since ordering and mismatch errors are
    only detectable on a later fragment.
    """
    lines = ["# name\texpected_code\tframes_hex(comma separated)"]
    for case in data["decode_errors"]:
        lines.append("\t".join([
            case["name"],
            case["code"],
            ",".join(case["frames_hex"]),
        ]))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    data = build()
    OUT.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
    print(f"wrote {OUT}")

    tsv = OUT.with_suffix(".tsv")
    tsv.write_text(build_tsv(data))
    print(f"wrote {tsv}")

    errs = OUT.parent / "decode_errors.tsv"
    errs.write_text(build_errors_tsv(data))
    print(f"wrote {errs}")
